version: "3.8"

services:
  web:
    build: .
    container_name: fastapi_clio
    ports:
      - "8011:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - redis-server
      - rabbitmq
      - postgres
    restart: always
    networks:
      - fastapi_clio_backend_network

  # PostgreSQL service
  postgres:
    image: postgres:13
    restart: always
    container_name: postgres_db_clio_fastapi
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5411:5432"
    networks:
      - fastapi_clio_backend_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5


  # pgAdmin service
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_clio_fastapi
    restart: always
    environment:
      # - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}  # Email to log in (e.g., admin@example.com)
      # - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}  # Password to log in
      - PGADMIN_DEFAULT_EMAIL=admin@example.com
      - PGADMIN_DEFAULT_PASSWORD=admin@123
    volumes:
      - pgadmin_data:/var/lib/pgadmin  # Persist pgAdmin data
    ports:
      - "5011:80"
    depends_on:
      - postgres
    networks:
      - fastapi_clio_backend_network

  redis-server:
    image: redis:latest
    container_name: redis_ai_fastapi_clio
    ports:
      - "6311:6379"
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    volumes:
      - redis_data:/data
    restart: always
    networks:
      - fastapi_clio_backend_network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq_ai_call_assistant
    ports:
      - "5611:5672"     # RabbitMQ AMQP
      - "15611:15672"   # RabbitMQ Management UI
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD}
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    restart: always
    networks:
      - fastapi_clio_backend_network

volumes:
  postgres_data:
  pgadmin_data:
  redis_data:
  rabbitmq_data:

networks:
  fastapi_clio_backend_network:
    external: true
